-- =============================================================================
-- ARCHIVO: crear_tablas.sql
-- =============================================================================
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PERSONA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DOCTOR CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PACIENTE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE HISTORIA_CLINICA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CONSULTA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MEDICINA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE RECETA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- 1. Tabla: Persona
CREATE TABLE PERSONA (
    NUM_DOCUMENTO       NUMBER(10)       CONSTRAINT PK_NUM_DOCUMENTO         PRIMARY KEY,
    TIPO_DOCUMENTO      VARCHAR2(3)      NOT NULL,
    NOMBRE_APELLIDO     VARCHAR2(50)     NOT NULL,
    FECHA_NACIMIENTO    DATE             NOT NULL,
    SEXO                CHAR(1)          NOT NULL CHECK (SEXO IN ('M','F')),
    DIRECCION           VARCHAR2(100)    NOT NULL,
    TELEFONO            NUMBER(10)       NOT NULL,
    CORREO_ELECTRONICO  VARCHAR2(100)    UNIQUE,
    ESTADO_CIVIL        VARCHAR2(30)     NOT NULL,
    TIPO_SANGRE         VARCHAR2(3)      NOT NULL,
    -- GENERALIZACION PARCIAL Y EXCLUSIVA
    TIPO_PERSONA        VARCHAR2(15)      NOT NULL CHECK (TIPO_PERSONA IN ('PACIENTE','DOCTOR','OTRO')),
    CONSTRAINT FK_TIPO_PERSONA UNIQUE (NUM_DOCUMENTO, TIPO_PERSONA)
);

-- 2. Tabla: Doctor
CREATE TABLE DOCTOR (
    ID_DOCTOR           VARCHAR2(10)     CONSTRAINT PK_ID_DOCTOR             PRIMARY KEY,
    FK_NUM_DOCUMENTO       NUMBER(10)    CONSTRAINT FK_PERSONA_DOCTOR        REFERENCES PERSONA(NUM_DOCUMENTO) NOT NULL,
    ESPECIALIDAD        VARCHAR2(20)     NOT NULL,
    NUMERO_LICENCIA     NUMBER(10)       NOT NULL UNIQUE,
    HORARIO_ATENCION    VARCHAR2(50)     NOT NULL,
    
    TIPO_PERSONA        VARCHAR2(15)     DEFAULT 'DOCTOR' NOT NULL CHECK (TIPO_PERSONA = 'DOCTOR'),
    CONSTRAINT FK_TIPO_DOCTOR FOREIGN KEY (FK_NUM_DOCUMENTO, TIPO_PERSONA) 
        REFERENCES PERSONA(NUM_DOCUMENTO, TIPO_PERSONA)
);

-- 3. Tabla: Paciente
CREATE TABLE PACIENTE (
    ID_PACIENTE         VARCHAR2(10)     CONSTRAINT PK_ID_PACIENTE           PRIMARY KEY,
    FK_NUM_DOCUMENTO       NUMBER(10)    CONSTRAINT FK_PERSONA_PACIENTE      REFERENCES PERSONA(NUM_DOCUMENTO) NOT NULL,
    OCUPACION           VARCHAR2(30)     NOT NULL,
    
    TIPO_PERSONA        VARCHAR2(15)     DEFAULT 'PACIENTE' NOT NULL CHECK (TIPO_PERSONA = 'PACIENTE'),
    CONSTRAINT FK_TIPO_PACIENTE FOREIGN KEY (FK_NUM_DOCUMENTO, TIPO_PERSONA) 
        REFERENCES PERSONA(NUM_DOCUMENTO, TIPO_PERSONA)
);

-- 4. Tabla: Historia_Clinica
CREATE TABLE HISTORIA_CLINICA (
    ID_HISTORIA          VARCHAR2(10)     CONSTRAINT PK_ID_HISTORIA         PRIMARY KEY,
    FK_ID_PACIENTE       VARCHAR2(10)     CONSTRAINT FK_ID_PACIENTE         REFERENCES PACIENTE(ID_PACIENTE) NOT NULL,
    ANTESCEDENTES        VARCHAR2(300)    NOT NULL,
    ALERGIAS             VARCHAR2(100)    NOT NULL,
    DIAGNOSTICOS_PREVIOS VARCHAR2(300)    NOT NULL,
    TRATAMIENTO          VARCHAR2(100)    NOT NULL
);

-- 5. Tabla: Consulta
CREATE TABLE CONSULTA (
    ID_CONSULTA          VARCHAR2(10)     CONSTRAINT PK_ID_CONSULTA         PRIMARY KEY,
    FK_ID_HISTORIA       VARCHAR2(10)     CONSTRAINT FK_ID_HISTORIA         REFERENCES HISTORIA_CLINICA(ID_HISTORIA) NOT NULL,
    FK_ID_DOCTOR         VARCHAR2(10)     CONSTRAINT FK_ID_DOCTOR           REFERENCES DOCTOR(ID_DOCTOR) NOT NULL,
    FECHA_HORA           DATE             NOT NULL,
    MOTIVO               VARCHAR2(100)    NOT NULL,
    SINTOMAS_ACTUALES    VARCHAR2(100)    NOT NULL,
    DIAGNOSTICO          VARCHAR2(100)    NOT NULL,
    PLAN_TERAPEUTICO     VARCHAR2(100)    NOT NULL,
    COSTO                DECIMAL(10,2)    NOT NULL CHECK (COSTO >= 0)
);

-- 6. Tabla: Medicina
CREATE TABLE MEDICINA (
    ID_MEDICINA          VARCHAR2(10)     CONSTRAINT PK_ID_MEDICINA         PRIMARY KEY,
    NOMBRE_COMERCIAL     VARCHAR2(30)     NOT NULL,
    COMPONENTE_ACTIVO    VARCHAR2(30)     NOT NULL,
    CONCENTRACION        VARCHAR2(30)     NOT NULL,
    PRESENTACION         VARCHAR2(30)     NOT NULL,
    STOCK                INT              NOT NULL CHECK (STOCK >= 0)
);

-- 7. Tabla: Receta
CREATE TABLE RECETA (
    ID_RECETA            VARCHAR2(10)     CONSTRAINT PK_ID_RECETA           PRIMARY KEY,
    FK_ID_CONSULTA       VARCHAR2(10)     CONSTRAINT FK_ID_CONSULTA         REFERENCES CONSULTA(ID_CONSULTA) NOT NULL,
    FK_ID_MEDICINA       VARCHAR2(10)     CONSTRAINT FK_ID_MEDICINA         REFERENCES MEDICINA(ID_MEDICINA) NOT NULL,
    DOSIS                VARCHAR2(30)     NOT NULL,
    DURACION             VARCHAR2(30)     NOT NULL
);
